"""initial schema

Revision ID: bf02e6073674
Revises: 
Create Date: 2026-07-16 20:21:11.145327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf02e6073674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('missing_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extra_skills', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.drop_column('extra_skills')
        batch_op.drop_column('missing_skills')
        batch_op.drop_column('matched_skills')

    # ### end Alembic commands ###
